---
- hosts: servers
  sudo: true
  user: vagrant
  tasks:
    - name: install httpd
      apt: name=apache2 state=installed
    - name: be sure httpd is running and enabled
      service: name=apache2 state=running enabled=yes

