---
  - name: install mysql
    apt: name={{ item }} state=latest
    with_items:
      - mysql-server
      - python-mysqldb
  - name: be sure mysql is running and enabled
    service: name=mysql state=started enabled=yes
  - name: update mysql root password for all root accounts
    mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
  - name: create db
    mysql_db:
      name: test_db
      login_user: root
      login_password: "{{ mysql_root_password }}"
      state: present
